<?php

use Illuminate\Database\Seeder;
use \Carbon\Carbon;

class OficialiasTableSeeder extends Seeder {
	public function run(){
		$now = Carbon::now();
		//DB::table('oficialias')->delete();
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01001',1,'VILLA DE AHOME',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01002',1,'VILLA GUSTAVO DIAZ ORDAZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01003',1,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01004',1,'TOPOLOBAMPO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01005',1,'SAN MIGUEL ZAPOTITLAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01006',1,'HIGUERAS DE ZARAGOZA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01007',1,'HERIBERTO VALDEZ ROMERO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01008',1,'PLAZA FATIMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01009',1,'I.M.S.S.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01010',1,'I.M.S.S. VILLA DE AHOME',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01885',1,'SAN MIGUEL ZAPOTITLAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01886',1,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01887',1,'TOPOLOBAMPO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01888',1,'PLAZA FATIMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01993',1,'SAN MIGUEL ZAPOTITLAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01994',1,'VILLA DE AHOME',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01996',1,'VILLA GUSTAVO DIAZ ORDAZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01997',1,'I.M.S.S.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01998',1,'PLAZA FATIMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['01999',1,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02001',2,'ANGOSTURA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02002',2,'ALHUEY',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02003',2,'COL. AGRICOLA MEXICO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02004',2,'COL. AGRICOLA INDEPENDENCIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02005',2,'GUSTAVO DIAZ ORDAZ (CPO. PLATA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02006',2,'LA ILAMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02007',2,'LA REFORMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02887',2,'LA REFORMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02888',2,'ANGOSTURA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02998',2,'LA REFORMA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['02999',2,'ANGOSTURA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03001',3,'BADIRAGUATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03002',3,'CIENEGA DE LOS LARA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03003',3,'HIGUERA DE ALVAREZ DE BORBOA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03004',3,'GUATENIPA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03005',3,'OTATILLOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03006',3,'SURUTATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03007',3,'SAN JOSE DEL LLANO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03008',3,'SAN LUIS GONZAGA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03009',3,'SAN NICOLAS DEL SITIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03010',3,'TAMEAPA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03011',3,'SAN JAVIER',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03888',3,'BADIRAGUATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['03999',3,'BADIRAGUATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04001',4,'CONCORDIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04002',4,'TEPUXTA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04003',4,'AGUACALIENTE DE GARATE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04004',4,'ZAVALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04005',4,'COPALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04006',4,'PANUCO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04007',4,'MESILLAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04008',4,'EL VERDE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04009',4,'SANTA LUCIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04887',4,'EL VERDE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04888',4,'CONCORDIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['04999',4,'CONCORDIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05001',5,'COSALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05002',5,'LA ILAMA (COMEDERO)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05003',5,'SAN JOSE DE LAS BOCAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05004',5,'GUADALUPE DE LOS REYES',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05005',5,'SANTA CRUZ DE ALAYA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05888',5,'COSALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['05999',5,'COSALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06000',6,'DIRECCION DEL REGISTRO CIVIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06001',6,'CENTRO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06002',6,'EL SALADO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06003',6,'COSTA RICA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06004',6,'BAILA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06005',6,'SANALONA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06006',6,'AGUARUTO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06007',6,'COL. TIERRA BLANCA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06008',6,'I.M.S.S.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06009',6,'ELDORADO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06012',6,'COL. LOMAS DE BOULEVARD',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06013',6,'SAN LORENZO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06015',6,'JESUS MARIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06016',6,'COL. SINALOA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06018',6,'HIGUERAS DE ABUYA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06020',6,'QUILA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06021',6,'VILLA ADOLFO LOPEZ MATEOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06022',6,'CULIACANCITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06023',6,'IMALA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06024',6,'LAS TAPIAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06025',6,'TEPUCHE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06026',6,'EMILIANO ZAPATA (EST. OBISPO)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06027',6,'TACUICHAMONA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06666',6,'DIRECCION DE REGISTRO CIVIL (ACLARACIONES)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06770',6,'DIRECCION DEL REGISTRO CIVIL (MODULO DF)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06777',6,'MODULO TIJUANA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06778',6,'DIRECCION DEL REGISTRO CIVIL (MODULO DF)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06885',6,'QUILA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06886',6,'AGUARUTO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06887',6,'I.M.S.S.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06888',6,'DIRECCION DE REGISTRO CIVIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06990',6,'QUILA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06991',6,'MOD. PLAZA SUR',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06992',6,'MOD. TIJUANA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06993',6,'AGUARUTO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06994',6,'MOD. UDO RC',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06995',6,'MOD. PLAZA AMERICAS RC',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06996',6,'MOD. H. AYUNTAMIENTO RC',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06997',6,'MOD. PLAZA FIESTA RC',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06998',6,'I.M.S.S.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['06999',6,'DIRECCION DEL REGISTRO CIVIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07001',7,'CHOIX',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07002',7,'AGUACALIENTE GRANDE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07003',7,'BACA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07004',7,'PICACHOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07005',7,'YECORATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07006',7,'SAN JAVIER',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07007',7,'EL TORO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07888',7,'CHOIX',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['07999',7,'CHOIX',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08001',8,'ELOTA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08002',8,'ZOQUITITAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08003',8,'LA CRUZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08004',8,'EL ESPINAL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08888',8,'LA CRUZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['08999',8,'LA CRUZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09001',9,'ESCUINAPA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09002',9,'LA CONCHA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09003',9,'PALMILLAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09004',9,'TEACAPAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09888',9,'ESCUINAPA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['09999',9,'ESCUINAPA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10001',10,'TEHUECO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10002',10,'MOCHICAHUI',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10003',10,'CHINOBAMPO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10004',10,'SAN BLAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10005',10,'CHARAY',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10006',10,'EL FUERTE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10007',10,'TETAROBA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10008',10,'JAHUARA II',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10886',10,'MOCHICAHUI',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10887',10,'SAN BLAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10888',10,'EL FUERTE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10997',10,'SAN BLAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10998',10,'MOCHICAHUI',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['10999',10,'EL FUERTE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11001',11,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11002',11,'BAMOA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11003',11,'ADOLFO RUIZ CORTINEZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11004',11,'TAMAZULA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11005',11,'LEON FONSECA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11006',11,'JUAN JOSE RIOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11007',11,'LA TRINIDAD',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11008',11,'LA BRECHA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11009',11,'EL BURRION',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11010',11,'DIF',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11011',11,'NIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11012',11,'SAN RAFAEL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11013',11,'IMSS JUAN JOSE RIOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11886',11,'DIF',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11887',11,'JUAN JOSE RIOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11888',11,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11996',11,'DIF',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11997',11,'MOD. PLAZA CRISTINA GVE.',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11998',11,'JUAN JOSE RIOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['11999',11,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12001',12,'LA NORIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12002',12,'COLONIA BENITO JUAREZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12003',12,'EL QUELITE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12004',12,'VILLA UNION',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12005',12,'EL RECODO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12006',12,'MARMOL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12007',12,'SIQUEROS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12008',12,'EL ROBLE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12009',12,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12010',12,'IMSS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12011',12,'ISLAS MARIAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12886',12,'IMSS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12887',12,'COLONIA BENITO JUAREZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12888',12,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12997',12,'IMSS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12998',12,'COLONIA BENITO JUAREZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['12999',12,'UNIDAD ADMINISTRATIVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13001',13,'MOCORITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13002',13,'EL VALLE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13003',13,'CERRO AGUDO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13004',13,'PERICOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13005',13,'SAN BENITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13006',13,'ROSA MORADA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13007',13,'MELCHOR OCAMPO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13887',13,'PERICOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13888',13,'MOCORITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13998',13,'PERICOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['13999',13,'MOCORITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14001',14,'EL ROSARIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14002',14,'POTRERILLOS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14003',14,'POZOLE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14004',14,'CHAMETLA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14005',14,'CACALOTAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14006',14,'MATATAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14007',14,'MALOYA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14008',14,'LA RASTRA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14009',14,'AGUAVERDE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14888',14,'EL ROSARIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['14999',14,'EL ROSARIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['15001',15,'GUAMUCHIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['15002',15,'VILLA BENITO JUAREZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['15888',15,'GUAMUCHIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['15999',15,'GUAMUCHIL',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16001',16,'SAN IGNACIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16002',16,'SAN JUAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16003',16,'SAN JAVIER',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16004',16,'IXPALINO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16005',16,'ESTACION DIMAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16006',16,'AJOYA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16007',16,'CONTRAESTACA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16008',16,'COYOTITAN',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16009',16,'PIAXTLA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16888',16,'SAN IGNACIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['16999',16,'SAN IGNACIO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17001',17,'SINALOA DE LEYVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17002',17,'OCORONI',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17003',17,'SAN JOSE DE GRACIA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17004',17,'GABRIEL LEYVA V. (TEMUCHINA)',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17005',17,'LLANO GRANDE',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17006',17,'ESTACION NARANJO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17007',17,'BACUBIRITO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17008',17,'SAN JOSE DE LAS DELICIAS',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17887',17,'ESTACION NARANJO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17888',17,'SINALOA DE LEYVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17998',17,'ESTACION NARANJO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['17999',17,'SINALOA DE LEYVA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18001',18,'NAVOLATO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18002',18,'SAN PEDRO',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18003',18,'VILLA ANGEL FLORES',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18004',18,'VILLA BENITO JUAREZ',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18005',18,'ALTATA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18006',18,'SATAYA',$now]);
		DB::insert('insert into oficialias (id, municipio_id, oficialia, created_at) values (?,?,?,?)', ['18007',18,'JUAN ALDAMA',$now]);
	}
}