<?php

use Illuminate\Database\Seeder;
use \Carbon\Carbon;

class ResponsableTableSeeder extends Seeder {
	public function run(){
		$now = Carbon::now();
		//DB::table('responsables')->delete();
		// datos de prueba
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [1,'ABRAHAM JARED CASILLAS GIL',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [2,'ADAN EDUARDO PEREGRINA MENENDEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [3,'AGUSTIN LOPEZ MARTINEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [4,'ALEJANDRA GPE. MENDOZA VEGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [5,'ALEJANDRINA IBARRA PAEZ','04002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [6,'ALFONSO AVILA OLAGE','14008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [7,'ALMA KARINA ZAZUETA ROJO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [8,'ALMA PATRICIA VALENZUELA VERDUZCO','01007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [9,'ALMA ROSA RODRIGUEZ SOLIS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [10,'ANA GABRIELA VIEDAS VALDEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [11,'ANA ISABEL ONTIVEROS AISPURO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [12,'ANA LINE INZUNZA QUEVEDO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [13,'ANGEL MIGUEL SAUCEDA MACHADO','18002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [14,'ANGELA ZAMORANO LOPEZ','01009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [15,'ARMIDA ARCE OLIVAS','13005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [16,'ARMIDA MARIA FERNANDA SANZ CASTRO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [17,'AZUCENA JIMENEZ ZAMANO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [18,'BALTAZAR MORENO HERNANDEZ','06018',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [19,'BEATRIZ HILDA CORRALES VALENZUELA','07006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [20,'BERTHA AGUILAR ROBLES',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [21,'BLADIMIR VEGA QUIÑONEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [22,'BLANCA YISSEL CARRILLO LOPEZ','06009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [23,'BRENDA ERENDIDA MEDINA CARDENAAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [24,'Brenda Erendida Medina Cárdenas',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [25,'BRENDA LIZBETH NAVIDAD ARIAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [26,'BRIANDA GISELLE CONTRERAS VALDEZ','16005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [27,'BRYSEIDA SELENE HERRERA ZAVALA','07005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [28,'CAMELIA GAXIOLA ACOSTA','01006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [29,'CARLOS FRANCISCO DIAZ LOPEZ','02007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [30,'CARLOS ISRAEL NUÑEZ BURGUEÑO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [31,'CARLOS YOVANI SANCHEZ SOTO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [32,'CARMINA ELIZABETH TELLEZ SALAZAR','06003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [33,'CATALINA ELIZABETH HERNANDEZ RODRIGUEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [34,'CATALINA GUADALUPE GUERRA TORRES','01001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [35,'CESAREO MONZON CARRILLO','03010',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [36,'CINTHYA ANAHI RODRIGUEZ BELTRAN',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [37,'CINTHYA GUADALUPE MEDINA URIAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [38,'CITLALITH ALEJANDRA DE LA CRUZ DE LOS RIOS','06016',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [39,'CLAUDIA JOSEFINA TIRADO SANDOVAL','12002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [40,'CLAUDIA LETICIA FUENTES DERAS','14009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [41,'CLAUDIA LILIANA BARRERAS PALAFOX',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [42,'CLAUDIELA MARLEN CHAVEZ LABRADA','13002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [43,'CONCEPCIÓN SERNA TIRADO','04003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [44,'CRISTHIAN ADAN CARRERA CABANILLAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [45,'CRISTIAN JOSUE RODRIGUEZ PEREZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [46,'CRUZ ALONSO IRIBE RAMIREZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [47,'DANIA GUADALUPE AGUILAR OSUNA','02003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [48,'DAVID GONZALEZ TORRES','14005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [49,'DAVID JOAQUIN CHAIDEZ ZAZUETA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [50,'DAVID RAMIREZ VALDEZ','06025',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [51,'DELIA ARACELY TREVIÑO MEDINA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [52,'DELIA EDITH GARCIA VALENZUELA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [53,'DEMETRIO LOPEZ NAVARRO','06002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [54,'DOLORES DEL CARMEN MENDOZA TORRES','14007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [55,'DORA ELENA GARCIA MEDINA','18005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [56,'EDITH CANDELARIA CABANILLAS ESPINOZA','08001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [57,'EDUARDO CRISTERNA GONZALEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [58,'EDUARDO LIZARRAGA GARCIA','04008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [59,'EDUARDO REYES ZAMORA','06004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [60,'EFRAIN BELTRAN ESPINOZA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [61,'EFRAIN LUGO CHAN',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [62,'ELVIA IMELDA MUÑOZ PETRIS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [63,'ELVIA PATRICIA GARCIA GRANADOS','12009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [64,'ELVIA ZARATE PIMENTEL',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [65,'ERIKA LIZETH BELTRAN MONRREAL',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [66,'ESCALANTE SALAZAR IRMA GABRIELA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [67,'EVA MARIBEL PICOS VALENZUELA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [68,'FABIOLA AYDEE MORENO YAÑEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [69,'FEDERICO LOPEZ LOPEZ','03007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [70,'FEDERICO OSUNA LIZARRAGA','12001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [71,'FIDEL PIÑA MORENO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [72,'FLERIDA TERESA SAINZ SANCHEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [73,'FRANCISCO JAVIER CECEÑA LOPEZ','10005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [74,'FRANCISCO JAVIER CRUZ ARCE',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [75,'FRANCISCO MANUEL VIEDAS REYES',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [76,'FRANCISCO OLEGARIO MARTINEZ ARAMBURO','12003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [77,'FRANCISCO RUBIO CAZARES',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [78,'FRANCISCO VAZQUEZ RAMIREZ','01002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [79,'GABRIEL LOPEZ VALENZUELA','06027',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [80,'GERMAN PERAZA PONCE','16001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [81,'GERMAN TOLEDO RAYGOZA','04007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [82,'GIOVANNI VERENICE MENDOZA AGUIRRE','05001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [83,'GLADYS LIZETH RODRIGUEZ GARCIA','09002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [84,'GONZALEZ HERNANDEZ URIEL',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [85,'GREGORIO VELIZ SANDOVAL','17005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [86,'GUADALUPE ALBERTO SOMERA PONCE','16002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [87,'GUADALUPE BORREGO CASTAÑEDA','14001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [88,'HEIDY JANETH CRISTERNA RAMIREZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [89,'IRANIA MARAI VILLA MEDINA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [90,'IRASEMA ALICIA RUIZ CAMACHO','06007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [91,'IRMA CLARISA SANDOVAL RIVERA','07001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [92,'IRMA LOPEZ RIVERA','13003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [93,'IRMA YOLANDA ORTEGA PINI','04005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [94,'ISELA ANTONIA COTA GASTELUM','11001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [95,'ISMAEL ORTIZ LOPEZ','03006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [96,'ITXEL DANIELA RENDON GUZMAN',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [97,'IVAN ALBERTO LUQUE','11002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [98,'JACQUELINE ROCIO ESTRADA SANCHEZ','06001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [99,'JAEL ROJAS LOPEZ','12005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [100,'JAQUELINE LOGAN GAXIOLA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [101,'JESUS ABEL SAUCEDA RAMIREZ','18007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [102,'JESUS ENRIQUE CHAVIRA RUIZ','07002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [103,'JESUS ENRIQUE CORVERA BURGOS','13004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [104,'JESUS LOPEZ ORTIZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [105,'JESUS OMAR BURGUEÑO CONTRERAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [106,'JESUS RAUL PARDINI LUNA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [107,'JESUS SAUCEDA SAUCEDA','17008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [108,'JESUS VICTORIANO AVILEZ SALAZAR','03002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [109,'JOAQUIN MONTES ARELLANES','03011',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [110,'JOEL PALAZUELOS RAMOS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [111,'JORGE HUMBERTO RUELAS SANDOVAL','10003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [112,'JORGE LUIS NAJERA CAREAGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [113,'JOSE ALONSO SANCHEZ CONTRERAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [114,'JOSE ANTONIO BALLESTEROS RODRIGUEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [115,'JOSE ARMANDO PEREZ SALAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [116,'JOSE CANDELARIO GAXIOLA VEGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [117,'JOSE CONSTANTINO LOPEZ SOLANO','11010',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [118,'JOSE DE JESUS FONSECA SALAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [119,'JOSE FRANCISCO CARRILLO FELIX','03004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [120,'JOSE JOEL LARRAÑAGA CAMPOS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [121,'JOSE RAMON LOPEZ TUASON','02001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [122,'JOSE TRINIDAD ANDRADE CHAVEZ','13007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [123,'JUAN ANTONIO FELIX VALENZUELA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [124,'JUAN ENRIQUE REYES VIZCARRA','04009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [125,'JUAN MANUEL BELTRAN RUIZ','06013',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [126,'JUANA ADRIANA NUÑEZ MORENO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [127,'JUDITH CAROLINA TOLOZA LOPEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [128,'JUDITH VERDUGO CARDENAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [129,'JULIAN DE JESUS MEZA VALENZUELA','03001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [130,'JULIO CESAR GALLARDO RUELAS','11011',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [131,'JULIO CESAR ZAMORA BOJORQUEZ','17007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [132,'KAREN JOSEFINA CRUZ CORONA','04006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [133,'KARINA AIDE SANCHEZ LOPEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [134,'KARINA HAYDEE SOTO ARELLANO','01008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [135,'KARLA EDITH CAMACHO ARMENTA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [136,'LAURA IMELDA HERRERA SERRANO','11006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [137,'LAURA LETICIA ARREDONDO CASTAÑEDA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [138,'LEONOR WAR GAXIOLA','11012',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [139,'LIDIA AGRAMON CARRAZCO','11003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [140,'LINDA ELIZABETH MEDINA MEDINA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [141,'LORENA GUADALUPE URIAS CHAVEZ','17003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [142,'LUCINDA MONTALVO ROJO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [143,'LUIS ALBERTO BARRAZA SEPULVEDA','17001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [144,'MAIROT ERENDIDA VALDEZ MACHADO','01004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [145,'MARGARITA FIGUEROA LEE',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [146,'MARGARITA RAMIREZ VALDEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [147,'MARIA ANTONIA BOLADO URIAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [148,'MARIA BEATRIZ ARAUJO AMARILLAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [149,'MARIA BELEN RIVERA JUAREZ','14006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [150,'MARIA CELINA NUÑEZ RENDON',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [151,'MARIA DE LOS ANGELES LÓPEZ CASTRO','03003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [152,'MARIA DE LOS ANGELES LOPEZ MASCAREÑO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [153,'MARIA DE LOS ANGELES MORAN GARCIA','12008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [154,'MARIA DOLORES BOJORQUEZ PEREZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [155,'MARIA ESMERALDA ZAZUETA VARGAS','18006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [156,'MARIA FRANCISCA SALAZAR URIARTE',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [157,'MARIA GUADALUPE LUNA MARTINEZ','05004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [158,'MARIA GUADALUPE RAMOS CALDERON','10002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [159,'MARIA ISABEL HERAS ESPINOZA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [160,'MARIA OFELIA AGRAZ CRUZ','01003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [161,'MARIA OLIVIA URIARTE RODRIGUEZ','06021',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [162,'MARIO ALBERTO MEDINA CARNERO','18003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [163,'MARIO CESAR GAXIOLA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [164,'MARISELA RUBIO LIZARRAGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [165,'MARISOL CHIQUETE PORTILLO','06006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [166,'MARSELA BRISEYDA SANCHEZ VALDEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [167,'MARTHA ALICIA VELAZQUEZ ROMERO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [168,'MARTHA ELENA ORTIZ GONZALEZ','17006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [169,'MARTIN FERNANDO VELAZQUEZ SANCHEZ','02005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [170,'MARTINA SILVIA ESPARZA ESPINOZA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [171,'MAYDO ERENDIDA MERCADO PORTILLO','03009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [172,'MAYRA YANETH OLIVAS BELTRAN',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [173,'MELESIO PEREZ ROJO','06015',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [174,'MELISSA ESPINOZA MADRID',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [175,'MICAELA NORIEGA BUELNA','16004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [176,'MIGUEL ANGEL LOERA BENITEZ','03008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [177,'MIGUEL ANGEL MORALES MEMBRILA','10008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [178,'MIGUEL RAYMUNDO ROMAN HERRERA','07004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [179,'MILTON VALDEZ ZAMORA','11005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [180,'MYRIAM DE JESUS BELTRAN LAZCANO','18004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [181,'MYRNA LOPEZ GUTIERREZ','02002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [182,'NATIVIDAD BARRON BUSH','09003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [183,'NICOLAS PARRA VILLALBA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [184,'NORMA SARMIENTO NAVARRO','07003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [185,'OCTAVIO ZAMORA MANJARREZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [186,'ODETTE GUADALUPE PUCHETA LIZARRAGA','12010',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [187,'OFELIA PAEZ ZATARAIN','04001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [188,'OLGA LYDIA LOPEZ ESPINOZA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [189,'PAOLA MARIA GUTIERREZ FJARDO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [190,'PATRICIA RUIZ GARCIA','04004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [191,'PAUL ANGULO MONTOYA','15001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [192,'PAZCACIO ALEJANDRO RIVERA PARRA','02004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [193,'PEDRO RENDON RODRIGUEZ','12006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [194,'PEDRO RODRIGUEZ ORTIZ','06024',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [195,'PLACIDA LORENA GASTELUM COVARRUBIAS','08003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [196,'PRISCILA MARIA TIZNADO HERNANDEZ','06022',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [197,'QUENIA MILAGROS AGUILAR CAMACHO','14002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [198,'QUINTIN AYALA ORDOÑEZ','11009',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [199,'RAFAEL QUINTERO LANDEROS','05005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [200,'RAMON HUMBERTO QUINTERO ARAUJO','03005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [201,'RAQUEL AIMEE QUIÑONEZ CURIEL',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [202,'RAQUEL LIZARRAGA RODRIGUEZ','12007',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [203,'RAUL MONTOYA CAMACHO','02006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [204,'RAUL RENE OSUNA RODRIGUEZ','12011',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [205,'RICARDO ERNESTO RAYGOZA ZUÑIGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [206,'RODRIGO LOPEZ LIZARRAGA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [207,'ROSA DEL CARMEN RODRIGUEZ VEGA','18001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [208,'ROSA ELENA LUGO PEDROZA','01005',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [209,'ROSA EVELIA MANCILLAS RODRIGUEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [210,'ROSA MARIA RIVERA RODRIGUEZ',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [211,'ROSALBA GUADALUPE RUBIO PAEZ','09001',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [212,'ROSALINDA BARAJAS CARRILLO','15002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [213,'ROSARIO CASTRO GUERRERO','13006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [214,'ROSARIO DE LOURDES ZAZUETA BELTRAN','06012',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [215,'RUBEN MORALES FELIX',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [216,'SAHAROULA ORTIZ ZAJOS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [217,'SANDRA CASTAÑEDA IRIARTE',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [218,'SANDRA MARIA AYALA HAM',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [219,'SARA CARRILLO JACOBO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [220,'SARA MARGARITA PEREZ PARRA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [221,'SERGIO GUEVARA CAMARGO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [222,'SERGIO RAFAEL CABALEIRO RAYGOZA','09004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [223,'SERGIO SAUL ESCARREGA SANCHEZ','06020',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [224,'SILVIA OLIVIA MENDOZA PADILLA',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [225,'SIMON ALFREDO JACOBO ZAZUETA','06026',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [226,'SINDYRA GPE. HERNANDEZ LIZARRAGA','14004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [227,'SOFIA GOMEZ CARDENAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [228,'SUJEI GARCIA CARDENAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [229,'TERESA ISABEL RAMOS TERRAZAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [230,'TERESITA DE JESUS CORONA GASTELUM',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [231,'VICTOR HUGO BELTRAN SALCIDO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [232,'VICTOR MANUEL CHAVEZ LANDEROS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [233,'VICTOR MANUEL MEZA SOTELO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [234,'VILLARREAL RAMIREZ MAXIMO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [235,'WALKIRIA AZARETTE SANCHEZ JUAREZ','06008',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [236,'WILFRIDO LEON LAMAS',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [237,'YENDI ALEJANDRA RUIZ LOPEZ','10006',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [238,'YENNY ZULEIMA BOJORQUEZ ARAMBURO',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [239,'YOLANDA VICTORIA AMARILLAS MORALES',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [240,'YURIVIA LICETH RAMIREZ ESPINOZA','17004',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [241,'ZAIDA LORENA GASPAR CALDERON',null,$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [242,'ZULET YULEMI SANCHEZ RODRIGUEZ','14003',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [243,'ZULEYDA JANETH LOPEZ ALVARADO','17002',$now]);
		DB::insert('insert into responsables (id, responsable, oficialia_id, created_at) values (?,?,?,?)', [244,'GOBIERNO DEL ESTADO',null,$now]);
		/*
		update responsables set responsable = 'FELIZARDO REYES VALDEZ' where oficialia_id like '01002';
		update responsables set responsable = 'ELIZABETH SOTO CHAVEZ' where oficialia_id like '01004';
		update responsables set responsable = 'SOCORRO GONZALEZ BURBOA' where oficialia_id like '01008';
		update responsables set responsable = 'AYMARA CANTO HERNANDEZ' where oficialia_id like '01009';
		update responsables set responsable = 'LUZ ESTHER LAIJA SAIZ' where oficialia_id like '02001';
		update responsables set responsable = 'JULIAN DE JESUS MEZA VALENZUELA (SUPLENCIA 03003)' where oficialia_id like '03003';
		update responsables set responsable = 'AMANDY ARIAS RODRIGUEZ' where oficialia_id like '04001';
		update responsables set responsable = 'MARIA DEL CARMEN SANCHEZ ACOSTA' where oficialia_id like '05001';
		update responsables set responsable = 'MARIA DEL CARMEN SANCHEZ ACOSTA (SUPLENCIA 05002)' where oficialia_id like '05002';
		update responsables set responsable = 'MARIA DEL CARMEN SANCHEZ ACOSTA (SUPLENCIA 05003)' where oficialia_id like '05003';
		update responsables set responsable = 'MYRIAM DE JESUS BELTRAN LAZCANO (SUPLENCIA 06005)' where oficialia_id like '06005';
		update responsables set responsable = 'PRISCILA MARIA TIZNADO HERNANDEZ (SUPLENCIA 06023)' where oficialia_id like '06023';
		update responsables set responsable = 'FLOR LLUVIANA MARQUEZ NIEBLAS' where oficialia_id like '07001';
		update responsables set responsable = 'ITZEL JACQUELINE CASTRO CARRASCO (SUPLENCIA 08002)' where oficialia_id like '08002';
		update responsables set responsable = 'ITZEL JACQUELINE CASTRO CARRASCO' where oficialia_id like '08003';
		update responsables set responsable = 'ITZEL JACQUELINE CASTRO CARRASCO (SUPLENCIA 08004)' where oficialia_id like '08004';
		update responsables set responsable = 'MARTHA VIRGINIA LOPEZ SANCHEZ' where oficialia_id like '09002';
		update responsables set responsable = 'NOE ADAN OSUNA RESENDIZ' where oficialia_id like '09003';
		update responsables set responsable = 'CARLOS ESTAVILLO MUÑOZ (SUPLENCIA 10001)' where oficialia_id like '10001';
		update responsables set responsable = 'MARIA GUADALUPE RAMOS CALDERON (SUPLENCIA 10004)' where oficialia_id like '10004';
		update responsables set responsable = 'CARLOS ESTAVILLO MUÑOZ' where oficialia_id like '10006';
		update responsables set responsable = 'CARLOS ESTAVILLO MUÑOZ (SUPLENCIA 10007)' where oficialia_id like '10007';
		update responsables set responsable = 'GRACIELA CRUZ PEREZ' where oficialia_id like '11002';
		update responsables set responsable = 'HERIBERTO COTA SANCHEZ' where oficialia_id like '11003';
		update responsables set responsable = 'ISELA ANTONIA COTA GASTELUM (SUPLENCIA 11004)' where oficialia_id like '11004';
		update responsables set responsable = 'MARIA SILVIA MERCADO SAENZ' where oficialia_id like '11006';
		update responsables set responsable = 'JULIO CESAR GALLARDO RUELAS (SUPLENCIA 11007)' where oficialia_id like '11007';
		update responsables set responsable = 'LEONOR WAR GAXIOLA (SUPLENCIA 11008)' where oficialia_id like '11008';
		update responsables set responsable = 'LEONOR WAR GAXIOLA (SUPLENCIA 11009)' where oficialia_id like '11009';
		update responsables set responsable = 'RAUL RENE OSUNA RODRIGUEZ' where oficialia_id like '12011';
		update responsables set responsable = 'IRASEMA SOSA VALENCIA' where oficialia_id like '13001';
		update responsables set responsable = 'JULIAN DE JESUS MEZA VALENZUELA (SUPLENCIA 13004)' where oficialia_id like '13004';
		update responsables set responsable = 'GERMAN PERAZA PONCE (SUPLENCIA 16003)' where oficialia_id like '16003';
		update responsables set responsable = 'GERMAN PERAZA PONCE (SUPLENCIA 16006)' where oficialia_id like '16006';
		update responsables set responsable = 'GUADALUPE ALBERTO SOMERA PONCE (SUPLENCIA 16007)' where oficialia_id like '16007';
		update responsables set responsable = 'GERMAN PERAZA PONCE (SUPLENCIA 16008)' where oficialia_id like '16008';
		update responsables set responsable = 'BRIANDA GISELLE CONTRERAS VALDEZ (SUPLENCIA 16009)' where oficialia_id like '16009';
		update responsables set responsable = 'BOENERGE FAVELA ACOSTA' where oficialia_id like '17001';
		update responsables set responsable = 'ALMA ZULEMA CHACON GARCIA' where oficialia_id like '17002';
		insert into responsables (id, responsable, oficialia_id) values (245,'MARIA DEL CARMEN SANCHEZ ACOSTA (SUPLENCIA 05002)','05002');
		insert into responsables (id, responsable, oficialia_id) values (246,'MARIA DEL CARMEN SANCHEZ ACOSTA (SUPLENCIA 05003)','05003');
		insert into responsables (id, responsable, oficialia_id) values (247,'MYRIAM DE JESUS BELTRAN LAZCANO (SUPLENCIA 06005)','06005');
		insert into responsables (id, responsable, oficialia_id) values (248,'PRISCILA MARIA TIZNADO HERNANDEZ (SUPLENCIA 06023)','06023');
		insert into responsables (id, responsable, oficialia_id) values (249,'ITZEL JACQUELINE CASTRO CARRASCO (SUPLENCIA 08002)','08002');
		insert into responsables (id, responsable, oficialia_id) values (250,'ITZEL JACQUELINE CASTRO CARRASCO (SUPLENCIA 08004)','08004');
		insert into responsables (id, responsable, oficialia_id) values (251,'CARLOS ESTAVILLO MUÑOZ (SUPLENCIA 10001)','10001');
		insert into responsables (id, responsable, oficialia_id) values (252,'MARIA GUADALUPE RAMOS CALDERON (SUPLENCIA 10004)','10004');
		insert into responsables (id, responsable, oficialia_id) values (253,'CARLOS ESTAVILLO MUÑOZ (SUPLENCIA 10007)','10007');
		insert into responsables (id, responsable, oficialia_id) values (254,'ISELA ANTONIA COTA GASTELUM (SUPLENCIA 11004)','11004');
		insert into responsables (id, responsable, oficialia_id) values (255,'JULIO CESAR GALLARDO RUELAS (SUPLENCIA 11007)','11007');
		insert into responsables (id, responsable, oficialia_id) values (256,'LEONOR WAR GAXIOLA (SUPLENCIA 11008)','11008');
		insert into responsables (id, responsable, oficialia_id) values (257,'IRASEMA SOSA VALENCIA','13001');
		insert into responsables (id, responsable, oficialia_id) values (258,'GERMAN PERAZA PONCE (SUPLENCIA 16003)','16003');
		insert into responsables (id, responsable, oficialia_id) values (259,'GERMAN PERAZA PONCE (SUPLENCIA 16006)','16006');
		insert into responsables (id, responsable, oficialia_id) values (260,'GUADALUPE ALBERTO SOMERA PONCE (SUPLENCIA 16007)','16007');
		insert into responsables (id, responsable, oficialia_id) values (261,'GERMAN PERAZA PONCE (SUPLENCIA 16008)','16008');
		insert into responsables (id, responsable, oficialia_id) values (262,'BRIANDA GISELLE CONTRERAS VALDEZ (SUPLENCIA 16009)','16009');
		*/
	}
}