<?php

use Illuminate\Database\Seeder;
use \Carbon\Carbon;

class ResponsableTableSeeder extends Seeder {
	public function run(){
		$now = Carbon::now();
		DB::table('responsables')->delete();
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [1,'ABRAHAM CASILLAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [2,'ACLARACIONES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [3,'ACTAS FORANEAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [4,'ALEJANDRA GUADALUPE MENDOZA VEGA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [5,'ALFREDO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [6,'ALHUEY',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [7,'ALMA ROSA RODRIGUEZ SOLIZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [8,'ALONSO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [9,'ANA KARINA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [10,'ANALINE INZUNZA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [11,'ARACELY',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [12,'ARCHIVO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [13,'AZUCENA JIMENEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [14,'BAJA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [15,'BODEGA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [16,'BODEGAUSE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [17,'BRENDA MEDINA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [18,'BRENDA MEDINA / JUAN FELIX',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [19,'CAJERO AMILCAR',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [20,'CAJERO CAMPIÑA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [21,'CAJERO MAZATLAN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [22,'CAPTURA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [23,'CATALINA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [24,'CATALINA ELIZABETH HERNANDEZ RODRIGUEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [25,'CELINA NUÑEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [26,'CHUYITA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [27,'CINTHYA RODRIGUEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [28,'CITLALITH',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [29,'CRISTIAN RODRIGUEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [30,'CRISTINA LOPEZ OTAÑEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [31,'CURP',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [32,'DAÑADO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [33,'DENISSE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [34,'DIGITAL',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [35,'DIRECCION',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [36,'DIRECCIÓN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [37,'DIRECCION ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [38,'DON FRANCISCO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [39,'DOÑA DOLORES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [40,'EDGARDO CASTAÑOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [41,'EDNA CASTRO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [42,'EDUARDO PEREGRINA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [43,'ELIZABETH',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [44,'FATIMA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [45,'FIDEL MONTOYA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [46,'FLERIDA SAINZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [47,'FRANCIS SALAZAR',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [48,'FRANCISCO MANUEL VIEDAS REYES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [49,'GABY ESCALANTE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [50,'GOBIERNO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [51,'HECTOR',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [52,'HERIBERTO VALDEZ R.',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [53,'HERIBERTO VALDEZ ROMERO, AHOME',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [54,'HEYDI',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [55,'HEYDI CRISTERNA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [56,'IMSS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [57,'INFORMES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [58,'IRACEMA ALICIA RUIZ CAMACHO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [59,'IRASEMA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [60,'IRMA GABRIELA ESCALANTE ZALAZAR',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [61,'ISABEL RAMOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [62,'ITZEL DANIELA RENDON GUZMAN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [63,'IVAN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [64,'IXPALINO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [65,'IXTEL',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [66,'JAQUELINE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [67,'JOAQUIN CHAIDEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [68,'JOEL',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [69,'JOEL LARRAÑAGA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [70,'JOEL PALAZUELOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [71,'JORGE AGUIRRE Y ARTURO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [72,'JORGE LUIS NAJERA CAREAGA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [73,'JOSE ANGEL',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [74,'JOSE GAXIOLA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [75,'JUAN ALDAMA (EL TIGRE)',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [76,'JUAN FELIX',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [77,'JUAN JOSE RIOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [78,'JUAN JOSE RIOS ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [79,'JUANA ADRIANA NUÑEZ MORENO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [80,'JUDITH',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [81,'JUDITH TOLOSA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [82,'JUDITH VERDUGO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [83,'JUDTIH TOLOSA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [84,'KARINA SANCHEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [85,'KARINA ZAZUETA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [86,'KARLA CAMACHO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [87,'KARLA ZAZUETA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [88,'LA CONCHA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [89,'LETICIA ARREDONDO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [90,'LETY',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [91,'LIC. JUAN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [92,'LUCINDA MONTALVO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [93,'MANUELA DE JESUS URIARTE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [94,'MARCELA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [95,'MARCELA SANCHEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [96,'MARCOS COTA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [97,'MARGARITA FIGUEROA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [98,'MARGARITA RAMIREZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [99,'MARIA ELENA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [100,'MARIA ISABEL HERAZ ESPINOZA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [101,'MARICELA RUBIO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [102,'MATRIMONIOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [103,'MELISSA MADRID',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [104,'MODULO DF',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [105,'NOTAS MARGINALES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [106,'OCTAVIO ZAMORA MANJARREZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [107,'OLGA LIDIA LOPEZ ESPINOZA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [108,'OMAR BURGUEÑO CONTRERAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [109,'PALMILLAS, ESCUINAPA.',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [110,'PAOLA MARIA GUTIERREZ FAJARDO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [111,'PATRICIA ACEVES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [112,'PLAZA FATIMA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [113,'PRFR. GARRIDO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [114,'PROCESO DE BAJA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [115,'PUESTO 6',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [116,'RAFAEL MACIAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [117,'ROSA EVELIA MANCILLAS RODRIGUEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [118,'ROSA MORADA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [119,'ROSARIO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [120,'ROSARIO DE LOURDES ZAZUETA BELTRAN',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [121,'ROSI RIVERA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [122,'RUIZ CORTINEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [123,'SANDRA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [124,'SARA MARGARITA PEREZ PARRA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [125,'SERVIDOR',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [126,'SERVIDOR 208',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [127,'SERVIDOR UTILERIAS SISTEMAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [128,'SILVIA ARAMBURO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [129,'SILVIA ESPARZA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [130,'SILVIA MENDOZA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [131,'SIQUEIROS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [132,'SUJEI GARCIA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [133,'TERESITA CORONA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [134,'TIMOTEO CARDENAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [135,'TURNERO MATRIMONIOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [136,'TURNERO NACIMIENTOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [137,'TURNOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [138,'ULISES',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [139,'URIEL GONZALEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [140,'USE',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [141,'VICTOR CHAVEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [142,'VICTOR HUGO AYON SANCHEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [143,'VILLA ADOLFO LOPEZ MATEOS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [144,'VIRIDIANA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [145,'YANETH',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [146,'YANETH OLIVAS',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [147,'YECORATO',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [148,'YENNI ZULEIMA BOJORQUEZ ARAMBURA',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [149,'YOVANI',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [150,'YOVANI SANCHEZ',$now]);
		DB::insert('insert into responsables (id, responsable, created_at) values (?, ?, ?)', [151,'ZAHAROULA ORTIZ',$now]);
	}
}